Add in test environment connections
dfe-analytical-services/eesyapi pull request #54
Opened 2024-10-22 12:48 UTC by rmbielby

# Brief overview of changes

This could get quite big. We need to add in the test environment examples, but also the environment needs to follow through appropriately in all the different components. And it'll be worth doing the same with api_version and dataset_version whilst we're on it.

## Why are these changes being made?

We need eesyapi to work across multiple environments: dev, test, preprod, prod

## Detailed description of changes

...

## Additional information for reviewers

...

## Issue ticket number/s and link

...

2024-10-22 22:37 UTC, cjrace commented
@rmbielby - test data sets are now published and can be viewed in the [test data catalogue](https://test.explore-education-statistics.service.gov.uk/data-catalogue?themeId=b9866689-fdbd-4cf5-4c7d-08dcf1c4abb4&publicationId=25d0e40b-643a-4f73-3ae5-08dcf1c4d57f&releaseId=0be920e7-8d1b-4cec-8a55-4289c9758e7a)

2024-10-23 17:17 UTC, cjrace requested changes
Not my most concise review!

Commented with some ideas that could be put into future issues, plus a handful minor of things to actually address in this PR

2024-10-24 12:00 UTC, rmbielby commented on vignettes/ees-api-workflow.Rmd
I've improved it a little. The bullet list of relevant IDs now auto-populates, so we can just copy from there to the code chunks. No idea how to evaluate a variable within a code chunk. Guessing there's a way, but don't want to risk sinking time into figuring that out right now.

2024-10-24 12:02 UTC, rmbielby commented on tests/testthat/test-preview_dataset.R
> +    10
Done

2024-10-24 12:19 UTC, rmbielby commented on R/api_url.R
> +  if (is.null(api_version)) {
Ok, have popped that un utils.R.

2024-10-24 12:25 UTC, rmbielby commented on R/examples.R
>  #' example_id("indicator", group = "attendance")
I feel like this is catered for by `default_ees_environment()`. I can't imagine the go to default environment not also being the example environment.

2024-10-24 12:25 UTC, rmbielby commented on R/get_dataset.R
> +  toggle_message(api_call, verbose = verbose)
Fair, have removed the one from get_dataset.

2024-10-24 12:27 UTC, rmbielby commented on R/examples.R
>  #' example_id("indicator", group = "attendance")
Or actually I've just made that an internal only function, so maybe there's scope for the two.

2024-10-24 13:00 UTC, rmbielby commented on R/api_url.R
> +  if (!(ees_environment %in% c("dev", "test", "preprod", "prod"))) {
Created the ees_environment validation check centrally now.

2024-10-24 13:18 UTC, rmbielby commented on R/examples.R
>  #' example_id("indicator", group = "attendance")
Added now

2024-10-24 13:21 UTC, rmbielby commented on R/post_dataset.R
> +#' example_id("filter_items_short", group = "attendance")
Fair, removed now.

2024-10-24 13:23 UTC, rmbielby commented on R/get_dataset.R
> +  toggle_message("Retrieved data", verbose = verbose)
Done

2024-10-24 13:37 UTC, rmbielby commented on R/get_meta.R
> +    ees_environment = NULL,
Yeah, they all get cascaded into api_url, so that's the point at which it's going to break if it is. Don't think it matters until that point.

2024-10-24 14:16 UTC, rmbielby commented on R/api_url.R
> +  if (!(ees_environment %in% c("dev", "test", "preprod", "prod"))) {
Done similar with a handful of others as will.

2024-10-24 14:24 UTC, rmbielby commented on R/post_dataset.R
> +      eesyapi::parse_api_dataset(
Yeah, think I've had that at the back of my mind, but was waiting until I had something I was confident in before going down that route. Bit of a core / big chunk of code to be moving around in this PR, so I'll vote for making a new ticket on the issues board on this one and picking it up in a fresh branch.

2024-10-24 14:53 UTC, cjrace commented on R/api_url.R
> +  if (!(ees_environment %in% c("dev", "test", "preprod", "prod"))) {
Nice!

2024-10-24 14:59 UTC, cjrace commented on vignettes/ees-api-workflow.Rmd
Yeah that's fair, this is an improvement for now

2024-10-24 15:05 UTC, cjrace commented on tests/testthat/test-preview_dataset.R
> +    10
Ah my bad, just ran the tests and I forgot that no indicators gives a warning. That flags in the tests, so actually it wants to be this instead:
```
  expect_equal(
    preview_dataset(example_id("dataset"), n_max = Inf) |> nrow(),
    query_dataset(example_id("dataset"), indicators = example_id("indicator")) |> nrow()
  )
```

2024-10-24 15:14 UTC, cjrace commented on R/post_dataset.R
> +      eesyapi::parse_api_dataset(
Sounds sensible - https://github.com/dfe-analytical-services/eesyapi/issues/58

2024-10-24 15:16 UTC, cjrace commented on R/examples.R
>  #' example_id("indicator", group = "attendance")
I think we've got confused here as I wasn't particularly precise in my wording, sorry... I was more thinking just giving an example of `example_id()` with the environment argument set!

Not against exporting the `ees_environment()` function you've made if there's a use, though currently can't see it used anywhere?

2024-10-24 15:21 UTC, cjrace commented on R/get_dataset.R
> +  toggle_message("Retrieved data", verbose = verbose)
Can get rid of the if() statement if you use `toggle_message()`

2024-10-24 15:47 UTC, rmbielby commented on R/examples.R
>  #' example_id("indicator", group = "attendance")
Ah, didn't go down that route as it felt a bit circular. example_id() takes the environment as a parameter, so I thought having it as a result as well would get a bit confusing.

2024-10-24 15:48 UTC, rmbielby commented on R/examples.R
>  #' example_id("indicator", group = "attendance")
Ah, think that's how I actually read your comment on the first sweep, but then misunderstood it when I came back to it!

2024-10-24 15:55 UTC, rmbielby commented on R/get_dataset.R
> +  toggle_message("Retrieved data", verbose = verbose)
But I like if statements... done anyway.

2024-10-24 16:29 UTC, cjrace approved these changes
All good to merge!

2024-10-24 16:32 UTC, merged